# Generated by Django 5.1.2 on 2024-10-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True},
        ),
    ]
