# Generated by Django 5.1.2 on 2024-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3app', '0003_alter_material_options_supplier_materials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
    ]
