# Generated by Django 5.1.2 on 2024-10-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3app', '0004_alter_material_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieswith',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='SuppliesTo',
        ),
        migrations.DeleteModel(
            name='SuppliesWith',
        ),
    ]
